obstacle_range: 5.5
raytrace_range: 3.5

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
robot_radius: 0.2

inflation_radius: 1.0


map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

global_frame: map
robot_base_frame: base_footprint

update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.5

static_map: true
