DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.6
  min_vel_x: 0.0

  max_vel_y: 0.2
  min_vel_y: -0.2

# The velocity when robot is moving in a straight line
  max_trans_vel:  0.6
  min_trans_vel:  0.15

  max_rot_vel: 1.0
  min_rot_vel: 0.5

  acc_lim_x: 1.8
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 0.4
  vx_samples: 30
  vy_samples: 0
  vth_samples: 30
  controller_frequency: 2

# Trajectory Scoring Parameters
  path_distance_bias: 45
  goal_distance_bias: 7.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
